// GENERATED by tools/fetch-rating-history.mjs — real FIDE monthly ratings. Do not edit by hand.
export type RatingPoint = { month: string; rating: number };
export type RatingHistory = { [key: string]: { name: string; fideId: string; months: RatingPoint[] } };

export const ratingHistory: RatingHistory = {
 "ABDULRAHEEM, Abdulrahman Akintoye": {
  "name": "ABDULRAHEEM, Abdulrahman Akintoye",
  "fideId": "8504563",
  "months": [
   {
    "month": "2017-07",
    "rating": 2337
   },
   {
    "month": "2017-08",
    "rating": 2337
   },
   {
    "month": "2017-09",
    "rating": 2337
   },
   {
    "month": "2017-10",
    "rating": 2337
   },
   {
    "month": "2017-11",
    "rating": 2337
   },
   {
    "month": "2017-12",
    "rating": 2337
   },
   {
    "month": "2018-01",
    "rating": 2337
   },
   {
    "month": "2018-02",
    "rating": 2337
   },
   {
    "month": "2018-04",
    "rating": 2337
   },
   {
    "month": "2018-05",
    "rating": 2337
   }
  ]
 },
 "Kigigha, Bomo Lovet": {
  "name": "Kigigha, Bomo Lovet",
  "fideId": "8500037",
  "months": [
   {
    "month": "2017-07",
    "rating": 2248
   },
   {
    "month": "2017-08",
    "rating": 2248
   },
   {
    "month": "2017-09",
    "rating": 2248
   },
   {
    "month": "2017-10",
    "rating": 2248
   },
   {
    "month": "2017-11",
    "rating": 2248
   },
   {
    "month": "2017-12",
    "rating": 2248
   },
   {
    "month": "2018-01",
    "rating": 2248
   },
   {
    "month": "2018-02",
    "rating": 2248
   },
   {
    "month": "2018-04",
    "rating": 2248
   },
   {
    "month": "2018-05",
    "rating": 2248
   }
  ]
 },
 "EKUNKE, Odey Goodness": {
  "name": "EKUNKE, Odey Goodness",
  "fideId": "8511888",
  "months": [
   {
    "month": "2017-07",
    "rating": 2196
   },
   {
    "month": "2017-08",
    "rating": 2196
   },
   {
    "month": "2017-09",
    "rating": 2196
   },
   {
    "month": "2017-10",
    "rating": 2196
   },
   {
    "month": "2017-11",
    "rating": 2196
   },
   {
    "month": "2017-12",
    "rating": 2196
   },
   {
    "month": "2018-01",
    "rating": 2196
   },
   {
    "month": "2018-02",
    "rating": 2196
   },
   {
    "month": "2018-04",
    "rating": 2196
   },
   {
    "month": "2018-05",
    "rating": 2196
   }
  ]
 },
 "EYETONGHAN, Denyefa Callistus": {
  "name": "EYETONGHAN, Denyefa Callistus",
  "fideId": "8511462",
  "months": [
   {
    "month": "2017-07",
    "rating": 2275
   },
   {
    "month": "2017-08",
    "rating": 2275
   },
   {
    "month": "2017-09",
    "rating": 2275
   },
   {
    "month": "2017-10",
    "rating": 2275
   },
   {
    "month": "2017-11",
    "rating": 2275
   },
   {
    "month": "2017-12",
    "rating": 2275
   },
   {
    "month": "2018-01",
    "rating": 2275
   },
   {
    "month": "2018-02",
    "rating": 2275
   },
   {
    "month": "2018-04",
    "rating": 2275
   },
   {
    "month": "2018-05",
    "rating": 2275
   }
  ]
 },
 "AIKHOJE, Odion": {
  "name": "AIKHOJE, Odion",
  "fideId": "8500240",
  "months": [
   {
    "month": "2017-07",
    "rating": 2252
   },
   {
    "month": "2017-08",
    "rating": 2252
   },
   {
    "month": "2017-09",
    "rating": 2252
   },
   {
    "month": "2017-10",
    "rating": 2252
   },
   {
    "month": "2017-11",
    "rating": 2252
   },
   {
    "month": "2017-12",
    "rating": 2252
   },
   {
    "month": "2018-01",
    "rating": 2252
   },
   {
    "month": "2018-02",
    "rating": 2252
   },
   {
    "month": "2018-04",
    "rating": 2252
   },
   {
    "month": "2018-05",
    "rating": 2252
   }
  ]
 },
 "OKHIPO, Bartholomew Emmanuel": {
  "name": "OKHIPO, Bartholomew Emmanuel",
  "fideId": "8509069",
  "months": [
   {
    "month": "2017-07",
    "rating": 2219
   },
   {
    "month": "2017-08",
    "rating": 2219
   },
   {
    "month": "2017-09",
    "rating": 2219
   },
   {
    "month": "2017-10",
    "rating": 2219
   },
   {
    "month": "2017-11",
    "rating": 2219
   },
   {
    "month": "2017-12",
    "rating": 2219
   },
   {
    "month": "2018-01",
    "rating": 2219
   },
   {
    "month": "2018-02",
    "rating": 2219
   },
   {
    "month": "2018-04",
    "rating": 2219
   },
   {
    "month": "2018-05",
    "rating": 2219
   }
  ]
 },
 "Olisa, Tennyson Ewomazino": {
  "name": "Olisa, Tennyson Ewomazino",
  "fideId": "8511390",
  "months": [
   {
    "month": "2017-07",
    "rating": 2301
   },
   {
    "month": "2017-08",
    "rating": 2301
   },
   {
    "month": "2017-09",
    "rating": 2301
   },
   {
    "month": "2017-10",
    "rating": 2301
   },
   {
    "month": "2017-11",
    "rating": 2301
   },
   {
    "month": "2017-12",
    "rating": 2301
   },
   {
    "month": "2018-01",
    "rating": 2301
   },
   {
    "month": "2018-02",
    "rating": 2301
   },
   {
    "month": "2018-04",
    "rating": 2301
   },
   {
    "month": "2018-05",
    "rating": 2301
   }
  ]
 },
 "LAPITE, Oluwadurotimi Opeoluwa": {
  "name": "LAPITE, Oluwadurotimi Opeoluwa",
  "fideId": "8503648",
  "months": [
   {
    "month": "2017-07",
    "rating": 2190
   },
   {
    "month": "2017-08",
    "rating": 2190
   },
   {
    "month": "2017-09",
    "rating": 2190
   },
   {
    "month": "2017-10",
    "rating": 2190
   },
   {
    "month": "2017-11",
    "rating": 2190
   },
   {
    "month": "2017-12",
    "rating": 2190
   },
   {
    "month": "2018-01",
    "rating": 2190
   },
   {
    "month": "2018-02",
    "rating": 2190
   },
   {
    "month": "2018-04",
    "rating": 2190
   },
   {
    "month": "2018-05",
    "rating": 2190
   }
  ]
 },
 "Balogun, Oluwafemi Daniel": {
  "name": "Balogun, Oluwafemi Daniel",
  "fideId": "8501246",
  "months": [
   {
    "month": "2017-07",
    "rating": 2212
   },
   {
    "month": "2017-08",
    "rating": 2212
   },
   {
    "month": "2017-09",
    "rating": 2212
   },
   {
    "month": "2017-10",
    "rating": 2212
   },
   {
    "month": "2017-11",
    "rating": 2212
   },
   {
    "month": "2017-12",
    "rating": 2212
   },
   {
    "month": "2018-01",
    "rating": 2212
   },
   {
    "month": "2018-02",
    "rating": 2212
   },
   {
    "month": "2018-04",
    "rating": 2212
   },
   {
    "month": "2018-05",
    "rating": 2212
   }
  ]
 },
 "EMMANUEL, Joy Idara": {
  "name": "EMMANUEL, Joy Idara",
  "fideId": "8513023",
  "months": [
   {
    "month": "2017-07",
    "rating": 2189
   },
   {
    "month": "2017-08",
    "rating": 2189
   },
   {
    "month": "2017-09",
    "rating": 2189
   },
   {
    "month": "2017-10",
    "rating": 2189
   },
   {
    "month": "2017-11",
    "rating": 2189
   },
   {
    "month": "2017-12",
    "rating": 2189
   },
   {
    "month": "2018-01",
    "rating": 2189
   },
   {
    "month": "2018-02",
    "rating": 2189
   },
   {
    "month": "2018-04",
    "rating": 2189
   },
   {
    "month": "2018-05",
    "rating": 2189
   }
  ]
 },
 "NYUIMA, Tersee Ferdinand": {
  "name": "NYUIMA, Tersee Ferdinand",
  "fideId": "8515263",
  "months": [
   {
    "month": "2017-07",
    "rating": 2248
   },
   {
    "month": "2017-08",
    "rating": 2248
   },
   {
    "month": "2017-09",
    "rating": 2248
   },
   {
    "month": "2017-10",
    "rating": 2248
   },
   {
    "month": "2017-11",
    "rating": 2248
   },
   {
    "month": "2017-12",
    "rating": 2248
   },
   {
    "month": "2018-01",
    "rating": 2248
   },
   {
    "month": "2018-02",
    "rating": 2248
   },
   {
    "month": "2018-04",
    "rating": 2248
   },
   {
    "month": "2018-05",
    "rating": 2248
   }
  ]
 },
 "AKINSEYE, Abiola Daniel": {
  "name": "AKINSEYE, Abiola Daniel",
  "fideId": "8503010",
  "months": [
   {
    "month": "2017-07",
    "rating": 2213
   },
   {
    "month": "2017-08",
    "rating": 2213
   },
   {
    "month": "2017-09",
    "rating": 2213
   },
   {
    "month": "2017-10",
    "rating": 2213
   },
   {
    "month": "2017-11",
    "rating": 2213
   },
   {
    "month": "2017-12",
    "rating": 2213
   },
   {
    "month": "2018-01",
    "rating": 2213
   },
   {
    "month": "2018-02",
    "rating": 2213
   },
   {
    "month": "2018-04",
    "rating": 2213
   },
   {
    "month": "2018-05",
    "rating": 2213
   }
  ]
 }
};
