// GENERATED by ProChess/tools/export-seed.mjs — do not edit by hand.
// Source: tournaments-data.js (DGT LiveChess exports) + fide-ratings.json (official FIDE list).
export type SeedPlayer = {
  lname: string; name: string; fideId: string; fed: string; title: string;
  standard: number; rapid: number; blitz: number; born: number | null;
};
export type SeedGame = { round: number; white: string; black: string; result: string; live: boolean };
export type SeedTournament = {
  slug: string; name: string; venue: string; timeControl: string; prizePool: string; games: SeedGame[];
};

export const seedPlayers: SeedPlayer[] = [
 {
  "lname": "ABDULRAHEEM, Abdulrahman Akintoye",
  "name": "ABDULRAHEEM, Abdulrahman Akintoye",
  "fideId": "8504563",
  "fed": "NGR",
  "title": "FM",
  "standard": 2316,
  "rapid": 2208,
  "blitz": 2193,
  "born": 1993
 },
 {
  "lname": "AKINSEYE, Abiola Daniel",
  "name": "AKINSEYE, Abiola Daniel",
  "fideId": "8503010",
  "fed": "NGR",
  "title": "FM",
  "standard": 2154,
  "rapid": 2150,
  "blitz": 0,
  "born": 1989
 },
 {
  "lname": "AIKHOJE, Odion",
  "name": "AIKHOJE, Odion",
  "fideId": "8500240",
  "fed": "NGR",
  "title": "IM",
  "standard": 2246,
  "rapid": 2292,
  "blitz": 2229,
  "born": 1971
 },
 {
  "lname": "EKUNKE, Odey Goodness",
  "name": "EKUNKE, Odey Goodness",
  "fideId": "8511888",
  "fed": "NGR",
  "title": "",
  "standard": 2280,
  "rapid": 2149,
  "blitz": 2138,
  "born": 2011
 },
 {
  "lname": "Olisa, Tennyson Ewomazino",
  "name": "Olisa, Tennyson Ewomazino",
  "fideId": "8511390",
  "fed": "NGR",
  "title": "FM",
  "standard": 2230,
  "rapid": 2058,
  "blitz": 2209,
  "born": 2003
 },
 {
  "lname": "EMMANUEL, Joy Idara",
  "name": "EMMANUEL, Joy Idara",
  "fideId": "8513023",
  "fed": "NGR",
  "title": "",
  "standard": 2175,
  "rapid": 2093,
  "blitz": 2003,
  "born": 2002
 },
 {
  "lname": "EYETONGHAN, Denyefa Callistus",
  "name": "EYETONGHAN, Denyefa Callistus",
  "fideId": "8511462",
  "fed": "NGR",
  "title": "FM",
  "standard": 2256,
  "rapid": 2131,
  "blitz": 2123,
  "born": 2002
 },
 {
  "lname": "OKHIPO, Bartholomew Emmanuel",
  "name": "OKHIPO, Bartholomew Emmanuel",
  "fideId": "8509069",
  "fed": "NGR",
  "title": "",
  "standard": 2246,
  "rapid": 2150,
  "blitz": 2004,
  "born": 1997
 },
 {
  "lname": "Kigigha, Bomo Lovet",
  "name": "Kigigha, Bomo Lovet",
  "fideId": "8500037",
  "fed": "NGR",
  "title": "FM",
  "standard": 2287,
  "rapid": 2280,
  "blitz": 2248,
  "born": 1982
 },
 {
  "lname": "LAPITE, Oluwadurotimi Opeoluwa",
  "name": "LAPITE, Oluwadurotimi Opeoluwa",
  "fideId": "8503648",
  "fed": "NGR",
  "title": "CM",
  "standard": 2228,
  "rapid": 2209,
  "blitz": 2195,
  "born": 1995
 },
 {
  "lname": "NYUIMA, Tersee Ferdinand",
  "name": "NYUIMA, Tersee Ferdinand",
  "fideId": "8515263",
  "fed": "NGR",
  "title": "",
  "standard": 2174,
  "rapid": 2099,
  "blitz": 1976,
  "born": 2007
 },
 {
  "lname": "Balogun, Oluwafemi Daniel",
  "name": "Balogun, Oluwafemi Daniel",
  "fideId": "8501246",
  "fed": "NGR",
  "title": "IM",
  "standard": 2220,
  "rapid": 2246,
  "blitz": 2178,
  "born": 1987
 }
];
export const seedTournaments: SeedTournament[] = [
 {
  "slug": "NIGERIA CHESS OLYMPIAD QUALIFIERS 2026 OPEN",
  "name": "NIGERIA CHESS OLYMPIAD QUALIFIERS 2026 OPEN",
  "venue": "chevron recreational centre gbagada, Nigeria",
  "timeControl": "90+30 · Classical",
  "prizePool": "₦500,000",
  "games": [
   {
    "round": 1,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "AKINSEYE, Abiola Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 1,
    "white": "AIKHOJE, Odion",
    "black": "EKUNKE, Odey Goodness",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 1,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "EMMANUEL, Joy Idara",
    "result": "1-0",
    "live": false
   },
   {
    "round": 1,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 1,
    "white": "Kigigha, Bomo Lovet",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "1-0",
    "live": false
   },
   {
    "round": 1,
    "white": "NYUIMA, Tersee Ferdinand",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 2,
    "white": "AKINSEYE, Abiola Daniel",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "0-1",
    "live": false
   },
   {
    "round": 2,
    "white": "LAPITE, Oluwadurotimi Opeoluwa",
    "black": "NYUIMA, Tersee Ferdinand",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 2,
    "white": "OKHIPO, Bartholomew Emmanuel",
    "black": "Kigigha, Bomo Lovet",
    "result": "0-1",
    "live": false
   },
   {
    "round": 2,
    "white": "EMMANUEL, Joy Idara",
    "black": "EYETONGHAN, Denyefa Callistus",
    "result": "0-1",
    "live": false
   },
   {
    "round": 2,
    "white": "EKUNKE, Odey Goodness",
    "black": "Olisa, Tennyson Ewomazino",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 2,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "AIKHOJE, Odion",
    "result": "1-0",
    "live": false
   },
   {
    "round": 3,
    "white": "AIKHOJE, Odion",
    "black": "AKINSEYE, Abiola Daniel",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 3,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "ABDULRAHEEM, Abdulrahman Akintoye",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 3,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "EKUNKE, Odey Goodness",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 3,
    "white": "Kigigha, Bomo Lovet",
    "black": "EMMANUEL, Joy Idara",
    "result": "0-1",
    "live": false
   },
   {
    "round": 3,
    "white": "NYUIMA, Tersee Ferdinand",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "0-1",
    "live": false
   },
   {
    "round": 3,
    "white": "Balogun, Oluwafemi Daniel",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "1-0",
    "live": false
   },
   {
    "round": 4,
    "white": "AKINSEYE, Abiola Daniel",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "0-1",
    "live": false
   },
   {
    "round": 4,
    "white": "OKHIPO, Bartholomew Emmanuel",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 4,
    "white": "EMMANUEL, Joy Idara",
    "black": "NYUIMA, Tersee Ferdinand",
    "result": "1-0",
    "live": false
   },
   {
    "round": 4,
    "white": "EKUNKE, Odey Goodness",
    "black": "Kigigha, Bomo Lovet",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 4,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "EYETONGHAN, Denyefa Callistus",
    "result": "1-0",
    "live": false
   },
   {
    "round": 4,
    "white": "AIKHOJE, Odion",
    "black": "Olisa, Tennyson Ewomazino",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 5,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "AKINSEYE, Abiola Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 5,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "AIKHOJE, Odion",
    "result": "0-1",
    "live": false
   },
   {
    "round": 5,
    "white": "Kigigha, Bomo Lovet",
    "black": "ABDULRAHEEM, Abdulrahman Akintoye",
    "result": "0-1",
    "live": false
   },
   {
    "round": 5,
    "white": "NYUIMA, Tersee Ferdinand",
    "black": "EKUNKE, Odey Goodness",
    "result": "0-1",
    "live": false
   },
   {
    "round": 5,
    "white": "Balogun, Oluwafemi Daniel",
    "black": "EMMANUEL, Joy Idara",
    "result": "1-0",
    "live": false
   },
   {
    "round": 5,
    "white": "LAPITE, Oluwadurotimi Opeoluwa",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "0-1",
    "live": false
   },
   {
    "round": 6,
    "white": "AKINSEYE, Abiola Daniel",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 6,
    "white": "EMMANUEL, Joy Idara",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "0-1",
    "live": false
   },
   {
    "round": 6,
    "white": "EKUNKE, Odey Goodness",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 6,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "NYUIMA, Tersee Ferdinand",
    "result": "1-0",
    "live": false
   },
   {
    "round": 6,
    "white": "AIKHOJE, Odion",
    "black": "Kigigha, Bomo Lovet",
    "result": "0-1",
    "live": false
   },
   {
    "round": 6,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "EYETONGHAN, Denyefa Callistus",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 7,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "AKINSEYE, Abiola Daniel",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 7,
    "white": "Kigigha, Bomo Lovet",
    "black": "Olisa, Tennyson Ewomazino",
    "result": "1-0",
    "live": false
   },
   {
    "round": 7,
    "white": "NYUIMA, Tersee Ferdinand",
    "black": "AIKHOJE, Odion",
    "result": "0-1",
    "live": false
   },
   {
    "round": 7,
    "white": "Balogun, Oluwafemi Daniel",
    "black": "ABDULRAHEEM, Abdulrahman Akintoye",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 7,
    "white": "LAPITE, Oluwadurotimi Opeoluwa",
    "black": "EKUNKE, Odey Goodness",
    "result": "1-0",
    "live": false
   },
   {
    "round": 7,
    "white": "OKHIPO, Bartholomew Emmanuel",
    "black": "EMMANUEL, Joy Idara",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 8,
    "white": "AKINSEYE, Abiola Daniel",
    "black": "EMMANUEL, Joy Idara",
    "result": "0-1",
    "live": false
   },
   {
    "round": 8,
    "white": "EKUNKE, Odey Goodness",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 8,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 8,
    "white": "AIKHOJE, Odion",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 8,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "NYUIMA, Tersee Ferdinand",
    "result": "1-0",
    "live": false
   },
   {
    "round": 8,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "Kigigha, Bomo Lovet",
    "result": "0-1",
    "live": false
   },
   {
    "round": 9,
    "white": "Kigigha, Bomo Lovet",
    "black": "AKINSEYE, Abiola Daniel",
    "result": "1-0",
    "live": false
   },
   {
    "round": 9,
    "white": "NYUIMA, Tersee Ferdinand",
    "black": "EYETONGHAN, Denyefa Callistus",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 9,
    "white": "Balogun, Oluwafemi Daniel",
    "black": "Olisa, Tennyson Ewomazino",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 9,
    "white": "LAPITE, Oluwadurotimi Opeoluwa",
    "black": "AIKHOJE, Odion",
    "result": "1/2-1/2",
    "live": false
   },
   {
    "round": 9,
    "white": "OKHIPO, Bartholomew Emmanuel",
    "black": "ABDULRAHEEM, Abdulrahman Akintoye",
    "result": "1-0",
    "live": false
   },
   {
    "round": 9,
    "white": "EMMANUEL, Joy Idara",
    "black": "EKUNKE, Odey Goodness",
    "result": "0-1",
    "live": false
   },
   {
    "round": 10,
    "white": "AKINSEYE, Abiola Daniel",
    "black": "EKUNKE, Odey Goodness",
    "result": "*",
    "live": false
   },
   {
    "round": 10,
    "white": "ABDULRAHEEM, Abdulrahman Akintoye",
    "black": "EMMANUEL, Joy Idara",
    "result": "*",
    "live": false
   },
   {
    "round": 10,
    "white": "AIKHOJE, Odion",
    "black": "OKHIPO, Bartholomew Emmanuel",
    "result": "*",
    "live": false
   },
   {
    "round": 10,
    "white": "Olisa, Tennyson Ewomazino",
    "black": "LAPITE, Oluwadurotimi Opeoluwa",
    "result": "*",
    "live": false
   },
   {
    "round": 10,
    "white": "EYETONGHAN, Denyefa Callistus",
    "black": "Balogun, Oluwafemi Daniel",
    "result": "*",
    "live": true
   },
   {
    "round": 10,
    "white": "Kigigha, Bomo Lovet",
    "black": "NYUIMA, Tersee Ferdinand",
    "result": "*",
    "live": false
   }
  ]
 }
];
