// Exports the real ProChess tournament + FIDE data into a TypeScript module that
// the Convex seed mutation imports. Regenerate after refreshing the FIDE list or
// adding new round folders:
//   node ProChess/tools/export-seed.mjs
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const DATA_JS = path.join(ROOT, "tournaments-data.js");
const FIDE_JSON = path.join(ROOT, "fide-ratings.json");
const OUT = path.join(ROOT, "web", "convex", "seedData.ts");

// --- tournaments ---
const src = fs.readFileSync(DATA_JS, "utf8");
const m = src.match(/window\.PROCHESS_TOURNAMENTS\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);
if (!m) throw new Error("Could not parse tournaments-data.js");
const tournaments = JSON.parse(m[1]);

const tList = Object.values(tournaments).map((t) => ({
  slug: t.id,
  name: t.name,
  venue: t.venue || "",
  timeControl: t.timeControl || "",
  prizePool: t.prizePool || "",
  games: t.rounds.flatMap((r) =>
    (r.pairings || [])
      .filter((pg) => pg.white?.lname && pg.black?.lname)
      .map((pg) => ({
        round: r.round,
        white: pg.white.lname,
        black: pg.black.lname,
        result: pg.result || "*",
        live: !!pg.live,
      }))
  ),
}));

// --- FIDE players ---
const fide = JSON.parse(fs.readFileSync(FIDE_JSON, "utf8"));
const pList = Object.values(fide.players).map((p) => ({
  lname: p.name, // FIDE "Surname, Given" form — matches pairing keys after normalization below
  name: p.name,
  fideId: String(p.fideId),
  fed: p.fed || "NGR",
  title: p.title || "",
  standard: p.standard || 0,
  rapid: p.rapid || 0,
  blitz: p.blitz || 0,
  born: p.born || null,
}));

// Pairing keys are display order ("Tersee Ferdinand Nyuima") while FIDE names are
// "Surname, Given". Normalize both to a canonical key so lookups line up.
const canon = (s) => s.toLowerCase().replace(/[^a-z ]/g, "").trim().split(/\s+/).sort().join(" ");
const byCanon = new Map(pList.map((p) => [canon(p.lname), p]));
for (const t of tList) {
  for (const g of t.games) {
    g.white = byCanon.get(canon(g.white))?.lname || g.white;
    g.black = byCanon.get(canon(g.black))?.lname || g.black;
  }
}

const out = `// GENERATED by ProChess/tools/export-seed.mjs — do not edit by hand.
// Source: tournaments-data.js (DGT LiveChess exports) + fide-ratings.json (official FIDE list).
export type SeedPlayer = {
  lname: string; name: string; fideId: string; fed: string; title: string;
  standard: number; rapid: number; blitz: number; born: number | null;
};
export type SeedGame = { round: number; white: string; black: string; result: string; live: boolean };
export type SeedTournament = {
  slug: string; name: string; venue: string; timeControl: string; prizePool: string; games: SeedGame[];
};

export const seedPlayers: SeedPlayer[] = ${JSON.stringify(pList, null, 1)};
export const seedTournaments: SeedTournament[] = ${JSON.stringify(tList, null, 1)};
`;

fs.writeFileSync(OUT, out);
const games = tList.reduce((n, t) => n + t.games.length, 0);
console.log(`Wrote ${OUT}`);
console.log(`  players: ${pList.length}  tournaments: ${tList.length}  games: ${games}`);
